name: Update Data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

concurrency: ci-${{ github.ref }}

jobs:
  release-data:
    name: Release Data
    runs-on: ubuntu-latest
    if: github.repository == '|3run0/mc856'
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-android: 'true'
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - run: poetry install
      - run: poetry run pypi_data_downloader download-releases release_data/ --limit=2000 --concurrency=20

      - uses: EndBug/add-and-commit@v9
        with:
          add: 'release_data/'
          # From https://github.community/t/github-actions-bot-email-address/17204/5
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          author_name: "commit-bot"
          message: "Scheduled data update from Github Actions"
          push: true
          fetch: false
